from enum import Enum


class Classification(str, Enum):
    MATCHED = "MATCHED"
    PAYMENT_MISSING = "PAYMENT_MISSING"
    PAYMENT_FAILED = "PAYMENT_FAILED"
    PAYMENT_DUPLICATE = "PAYMENT_DUPLICATE"
    PAYMENT_AMOUNT_MISMATCH = "PAYMENT_AMOUNT_MISMATCH"
    PAYMENT_CURRENCY_MISMATCH = "PAYMENT_CURRENCY_MISMATCH"
    SETTLEMENT_MISSING = "SETTLEMENT_MISSING"
    SETTLEMENT_AMOUNT_MISMATCH = "SETTLEMENT_AMOUNT_MISMATCH"
    SETTLEMENT_CURRENCY_MISMATCH = "SETTLEMENT_CURRENCY_MISMATCH"
    INVALID_RECORD = "INVALID_RECORD"
    REQUIRES_MANUAL_REVIEW = "REQUIRES_MANUAL_REVIEW"

